# Summary statistics for the executive analysis sample (Table 1).
# Descriptive only (no estimation). Emits a house-style booktabs fragment
# matching the litigation_composition.tex mould (double rules, \multicolumn
# panel headers, readable labels). Rows are the actual analysis variables:
# the litigation levels, the instrument, the treatment, the mayoral outcomes
# (2024-2020 change), and the predetermined controls. Per-variable N is the
# non-missing count in executive_margin_design.csv.

suppressPackageStartupMessages({
  user_lib <- "C:/Users/naral/R/win-library/4.6"
  if (dir.exists(user_lib)) .libPaths(c(user_lib, .libPaths()))
  library(data.table)
})

# ---- path detection (RStudio + Rscript) ----
args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
SCRIPT_DIR <- if (length(file_arg) > 0) {
  dirname(normalizePath(sub("^--file=", "", file_arg[1])))
} else getwd()
PROJECT_ROOT   <- normalizePath(file.path(SCRIPT_DIR, "..", ".."))
ESTIMATION_DIR <- file.path(PROJECT_ROOT, "data", "estimation")
TEX_DIR        <- file.path(PROJECT_ROOT, "output", "tables", "tex")
dir.create(TEX_DIR, recursive = TRUE, showWarnings = FALSE)

df <- fread(file.path(ESTIMATION_DIR, "executive_margin_design.csv"),
            colClasses = list(character = c("state", "municipality_id_tse", "cluster_id")))
cat(sprintf("Loaded design: %d municipalities\n", nrow(df)))

# ---- row spec: variable, label, decimals ----
# Each entry: column name in the design, human-readable label, sprintf digits.
spec <- list(
  panelA = list(
    title = "Litigation and the instrument",
    rows = list(
      c("competition_lawsuits_2020",                 "Adversarial lawsuits, 2020 (count)",        "1"),
      c("delta_log1p_competition_lawsuits_2024_2020","Treatment: $\\Delta\\log(1+\\text{lawsuits})$, 2020--2024", "3"),
      c("bartik_iv_2020_2024",                       "Instrument: shift-share exposure ($Z_m$)",  "3")
    )
  ),
  panelB = list(
    title = "Mayoral electoral outcomes (2024 $-$ 2020 change)",
    rows = list(
      c("delta_margin_top1_top2_2024_2020",          "Winner$-$runner-up margin",                 "3"),
      c("delta_runnerup_vote_share_2024_2020",       "Runner-up vote share",                      "3"),
      c("delta_effective_n_candidates_vote_2024_2020","Effective number of candidates",           "3"),
      c("delta_blank_rate_2024_2020",                "Blank-vote rate",                           "3"),
      c("delta_null_rate_2024_2020",                 "Null-vote rate",                            "3"),
      c("delta_valid_vote_rate_2024_2020",           "Valid-vote rate",                           "3")
    )
  ),
  panelC = list(
    title = "Predetermined controls",
    rows = list(
      c("log_pop_2010",                 "Log population, 2010",                  "3"),
      c("urban_share_2010",             "Urban share, 2010",                     "3"),
      c("log_income_pc_2010",           "Log income per capita, 2010",           "3"),
      c("higher_educ_share_2010",       "Higher-education share, 2010",          "3"),
      c("margin_2016",                  "Victory margin, 2016",                  "3")
    )
  )
)

fmt_n   <- function(n) formatC(n, format = "d", big.mark = ",")
fmt_num <- function(x, d) formatC(x, format = "f", digits = as.integer(d), big.mark = ",")

row_stats <- function(col, label, d) {
  stopifnot(col %in% names(df))
  x <- as.numeric(df[[col]])
  x <- x[is.finite(x)]
  n  <- length(x)
  mu <- mean(x); sdv <- sd(x)
  qs <- quantile(x, c(.10, .50, .90), names = FALSE, type = 7)
  sprintf("%s & %s & %s & %s & %s & %s & %s \\\\",
          label, fmt_n(n), fmt_num(mu, d), fmt_num(sdv, d),
          fmt_num(qs[1], d), fmt_num(qs[2], d), fmt_num(qs[3], d))
}

L <- c(
  "% Auto-generated by code/04_analysis/09_summary_statistics.R",
  "% Do not edit manually -- rerun the generating script to update",
  "",
  "\\begin{tabular}{lcccccc}",
  "\\toprule\\toprule",
  " & $N$ & Mean & SD & P10 & Median & P90 \\\\",
  "\\midrule"
)
for (p in spec) {
  L <- c(L, sprintf("\\multicolumn{7}{l}{\\textit{%s}} \\\\", p$title))
  for (r in p$rows) L <- c(L, row_stats(r[1], r[2], r[3]))
  if (!identical(p$title, spec$panelC$title)) L <- c(L, "\\midrule")
}
L <- c(L, "\\bottomrule\\bottomrule", "\\end{tabular}")

out <- file.path(TEX_DIR, "sample_summary_statistics.tex")
writeLines(L, out)
cat(sprintf("Wrote %s (%d rows)\n", out, length(L)))
