"""
WHO the consolidation favours: the 2024 mayoral field profiled BY VOTE RANK
(winner / runner-up / rest of field), on political standing and demographics.

Purpose (descriptive complement to the consolidation result, Nara 2026-07-07).
The IV shows litigation WIDENS the top-two mayoral margin (the winner pulls away
from the runner-up) while leaving the vote-weighted demographic mix of winners
UNMOVED (the representation null). This descriptive puts a face on that pair of
findings: it asks who the favoured candidate actually IS relative to the runner-up.
The answer is that the axis separating them is INCUMBENCY / political standing,
NOT gender / race / education / age -- the top-two are demographic near-twins.
So reinforcing the leader entrenches incumbency without touching descriptive
representation, which is mechanically WHY the representation effect is null.

Purely descriptive (a 2024 cross-sectional portrait); no causal claim, no
regression -- so it lives in Python. Rank is vote rank within a municipality's
mayoral race, exactly as in 10_candidate_finance.py (sort on candidate_vote_total).

Input : data/clean/candidate_vote_panel.csv   (per-candidate votes + traits + history)
Output: output/tables/descriptives/candidate_rank_profile.csv   (source of truth; both cycles)
        output/tables/tex/candidate_rank_profile.tex            (deck fragment, 2024)
"""
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
PANEL = ROOT / "data/clean/candidate_vote_panel.csv"
CSV_OUT = ROOT / "output/tables/descriptives/candidate_rank_profile.csv"
TEX_OUT = ROOT / "output/tables/tex/candidate_rank_profile.tex"

YEARS = (2020, 2024)
DECK_YEAR = 2024

# (column in panel, human label, kind) -- kind drives formatting & the block it sits in
STANDING = [
    ("is_incumbent_from_prior", "Incumbent (won this seat last cycle)", "pct"),
    ("is_prior_winner",         "Prior election winner",               "pct"),
    ("is_first_time",           "First-time candidate",                "pct"),
]
DEMOG = [
    ("is_female",            "Female",            "pct"),
    ("is_nonwhite",          "Non-white",         "pct"),
    ("is_higher_education",  "Higher education",  "pct"),
    ("candidate_age",        "Age (years)",       "years"),
]
ALL_ROWS = STANDING + DEMOG

GROUPS = {1: "winner", 2: "runner_up"}          # rank 1 / rank 2; 3+ = rest of field


def load_ranked() -> pd.DataFrame:
    """Per-candidate mayoral rows, tagged with within-race vote rank & group."""
    df = pd.read_csv(PANEL, encoding="utf-8-sig", dtype={"municipality_id_tse": str})
    df = df[df["office_group"] == "executive"].copy()
    df["candidate_vote_total"] = pd.to_numeric(df["candidate_vote_total"], errors="coerce")
    df = df.sort_values(["election_year", "municipality_id_tse", "candidate_vote_total"],
                        ascending=[True, True, False])
    df["vote_rank"] = (df.groupby(["election_year", "municipality_id_tse"])
                         .cumcount() + 1)
    df["rank_group"] = df["vote_rank"].map(GROUPS).fillna("rest_of_field")
    return df


def profile(df: pd.DataFrame, year: int) -> pd.DataFrame:
    """Mean of each trait by rank group for one cycle (percent for 0/1 flags)."""
    sub = df[df["election_year"] == year]
    order = ["winner", "runner_up", "rest_of_field"]
    means = sub.groupby("rank_group")[[c for c, _, _ in ALL_ROWS]].mean().reindex(order)
    n = sub.groupby("rank_group").size().reindex(order).rename("n_candidates")
    out = means.T.copy()
    for c, _, kind in ALL_ROWS:
        if kind == "pct":
            out.loc[c] = out.loc[c] * 100.0
    out.loc["n_candidates"] = n
    out["year"] = year
    return out.reset_index().rename(columns={"index": "measure"})


def write_csv(df: pd.DataFrame) -> None:
    frames = [profile(df, y) for y in YEARS]
    long = pd.concat(frames, ignore_index=True)
    label = {c: lab for c, lab, _ in ALL_ROWS}
    label["n_candidates"] = "N candidates"
    long["measure_label"] = long["measure"].map(label)
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    long.to_csv(CSV_OUT, index=False)
    print(f"Wrote {CSV_OUT}")


def _cells(vals, kind):
    if kind == "pct":
        return " & ".join(f"{v:.1f}" for v in vals)
    if kind == "years":
        return " & ".join(f"{v:.1f}" for v in vals)
    return " & ".join(f"{v:,.0f}" for v in vals)


def write_tex(df: pd.DataFrame) -> None:
    p = profile(df, DECK_YEAR).set_index("measure")
    cols = ["winner", "runner_up", "rest_of_field"]

    def rowline(col, label, kind, band=False, indent=True):
        vals = [p.loc[col, c] for c in cols]
        lead = "\\quad " if indent else ""
        pre = "\\rowcolor{mylight}\n" if band else ""
        return f"{pre}{lead}{label} & {_cells(vals, kind)} \\\\"

    lines = [
        f"% Auto-generated by code/04_analysis/10_candidate_rank_profile.py ({DECK_YEAR} mayoral)",
        "% Do not edit manually -- rerun the generating script to update",
        "",
        "\\begin{tabular}{lccc}",
        "\\toprule\\toprule",
        " & \\textbf{Winner} & \\textbf{Runner-up} & \\textbf{Rest of} \\\\",
        " & \\scriptsize{(1st)} & \\scriptsize{(2nd)} & \\scriptsize{field} \\\\",
        "\\midrule",
        "\\multicolumn{4}{l}{\\textit{Political standing}} \\\\",
    ]
    for col, label, kind in STANDING:
        lines.append(rowline(col, label, kind,
                             band=(col == "is_incumbent_from_prior")))
    lines += ["\\midrule", "\\multicolumn{4}{l}{\\textit{Demographics}} \\\\"]
    for col, label, kind in DEMOG:
        lines.append(rowline(col, label, kind))
    lines += [
        "\\midrule",
        rowline("n_candidates", "$N$ candidates", "int", indent=False),
        "\\bottomrule\\bottomrule",
        "\\end{tabular}",
    ]
    TEX_OUT.parent.mkdir(parents=True, exist_ok=True)
    TEX_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {TEX_OUT}")


def main() -> None:
    df = load_ranked()
    write_csv(df)
    write_tex(df)
    # console read-out of the headline contrast
    p = profile(df, DECK_YEAR).set_index("measure")
    print(f"\n{DECK_YEAR} mayoral, winner vs runner-up:")
    print(f"  Sitting incumbent : {p.loc['is_incumbent_from_prior','winner']:.1f}% "
          f"vs {p.loc['is_incumbent_from_prior','runner_up']:.1f}%")
    print(f"  Female            : {p.loc['is_female','winner']:.1f}% "
          f"vs {p.loc['is_female','runner_up']:.1f}%")
    print(f"  Non-white         : {p.loc['is_nonwhite','winner']:.1f}% "
          f"vs {p.loc['is_nonwhite','runner_up']:.1f}%")


if __name__ == "__main__":
    main()
