r"""
17_electorate_descriptives.py

The electorate and voting behaviour, by election year -- a reproducible version
of the "scale of the phenomenon" table. National aggregates are summed from the
municipality administrative returns; the Delta% column is the relative
2020->2024 change in the underlying count, with significance from a paired
t-test across the municipalities present in both cycles.

Source:
  data/clean/electoral_admin_outcomes.csv  -- municipality x year admin returns

Writes:
  output/tables/tex/electorate_macros.tex  -- \providecommand/\renewcommand macros
  output/tables/tex/electorate_frame.tex   -- the beamer frame fragment
"""

import pandas as pd
import numpy as np
from scipy import stats
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TEX = ROOT / "output" / "tables" / "tex"
TEX.mkdir(parents=True, exist_ok=True)

d = pd.read_csv(ROOT / "data" / "clean" / "electoral_admin_outcomes.csv")

# Each metric: (count column, denominator for its share or None).
# turnout / abstention are shares of registered voters; blank / null / valid
# are shares of those who voted (total_votes).
METRICS = {
    "Reg":   ("registered_voters", None),
    "Vot":   ("turnout_count",     "registered_voters"),
    "Abs":   ("abstentions_count", "registered_voters"),
    "Blank": ("blank_votes",       "total_votes"),
    "Null":  ("null_votes",        "total_votes"),
    "Valid": ("valid_votes",       "total_votes"),
}

YR = {2020: "A", 2024: "B"}
d20 = d[d.election_year == 2020]
d24 = d[d.election_year == 2024]

# Balanced panel of municipalities present in both cycles (for paired tests).
both = (d20.merge(d24, on="municipality_id_tse", suffixes=("_20", "_24")))


def stars(p):
    if pd.isna(p):
        return ""
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


def millions(v):
    return f"{v / 1e6:.1f}"            # one decimal -> dots align under \r


def share_pct(num, den):
    return f"{100 * num / den:.1f}"    # one decimal -> dots align under \r


def diff_cell(a, b, p):
    """Relative %% change a->b; fixed-width star box keeps the %% aligned."""
    rel = 100 * (b - a) / a
    box = f"\\makebox[1.4em][l]{{$^{{{stars(p)}}}$}}"
    return f"{'+' if rel >= 0 else ''}{rel:.1f}\\%{box}"


M = ["% Auto-generated by code/04_analysis/17_electorate_descriptives.py — do not edit by hand."]


def emit(name, val):
    M.append(f"\\providecommand{{\\{name}}}{{}}\\renewcommand{{\\{name}}}{{{val}}}")


for tag, (col, den) in METRICS.items():
    tot20, tot24 = d20[col].sum(), d24[col].sum()
    emit(f"E{tag}A", millions(tot20))
    emit(f"E{tag}B", millions(tot24))
    if den is not None:
        emit(f"E{tag}ShareA", share_pct(tot20, d20[den].sum()))
        emit(f"E{tag}ShareB", share_pct(tot24, d24[den].sum()))
    # paired test on the municipality-level count
    p = stats.ttest_rel(both[f"{col}_24"], both[f"{col}_20"]).pvalue
    emit(f"E{tag}Diff", diff_cell(tot20, tot24, p))

(TEX / "electorate_macros.tex").write_text("\n".join(M) + "\n", encoding="utf-8")


# ----------------------------------------------------------------------
# Frame fragment.  Count and share live in separate right-aligned columns
# (units in the header) so every decimal point and every %% lines up.
# ----------------------------------------------------------------------
frame = r"""% Auto-generated by code/04_analysis/17_electorate_descriptives.py — do not edit by hand.
% Requires: \input electorate_macros.tex in the preamble.
\begin{frame}{The Electorate --- Turnout and the Spoilt-Vote Margin}
\centering
\footnotesize
\renewcommand{\arraystretch}{1.15}
\begin{tabular}{l r r r r r}
  \toprule
   & \multicolumn{2}{c}{2020} & \multicolumn{2}{c}{2024} & \\
  \cmidrule(lr){2-3}\cmidrule(lr){4-5}
   & \multicolumn{1}{c}{M} & \multicolumn{1}{c}{\%}
   & \multicolumn{1}{c}{M} & \multicolumn{1}{c}{\%}
   & \multicolumn{1}{c}{$\Delta$\%} \\
  \midrule
  Registered voters       & \ERegA   &        & \ERegB   &        & \ERegDiff \\
  \textbf{Voted}          & \textbf{\EVotA} & \EVotShareA & \textbf{\EVotB} & \EVotShareB & \EVotDiff \\
  \textbf{Did not vote}   & \textbf{\EAbsA} & \EAbsShareA & \textbf{\EAbsB} & \EAbsShareB & \EAbsDiff \\
  \multicolumn{6}{l}{\textit{Among those who voted}} \\
  \quad Blank votes       & \EBlankA & \EBlankShareA & \EBlankB & \EBlankShareB & \EBlankDiff \\
  \quad Null votes        & \ENullA  & \ENullShareA  & \ENullB  & \ENullShareB  & \ENullDiff \\
  \quad Valid votes       & \EValidA & \EValidShareA & \EValidB & \EValidShareB & \EValidDiff \\
  \bottomrule
\end{tabular}

\vspace{4pt}
\begin{block}{}
  \footnotesize
  National electorate, aggregated from municipal administrative returns
  (counts in millions; shares: turnout / abstention out of registered voters,
  blank / null / valid out of those who voted). Compulsory voting anchors
  turnout above 76\%, rising to \EVotShareB\% in 2024. The
  \textbf{blank and null votes} are the residual spoilt-vote margin ---
  \EBlankShareA\%\,$+$\,\ENullShareA\% of voters in 2020, falling to
  \EBlankShareB\%\,$+$\,\ENullShareB\% in 2024 --- and the channel through which
  electoral litigation can move outcomes without changing who turns out.
  \par\smallskip
  {\scriptsize $\Delta$\% is the relative 2020$\to$2024 change in the underlying
  count; significance from a paired $t$-test across the municipalities present in
  both cycles. $^{***}p<.01$, $^{**}p<.05$, $^{*}p<.10$.}
\end{block}
\end{frame}"""

(TEX / "electorate_frame.tex").write_text(frame + "\n", encoding="utf-8")

# ----------------------------------------------------------------------
# Console
# ----------------------------------------------------------------------
print(f"{'metric':18s} | {'2020':>9s} {'2024':>9s} | {'share20':>8s} {'share24':>8s} | diff")
print("-" * 70)
for tag, (col, den) in METRICS.items():
    tot20, tot24 = d20[col].sum(), d24[col].sum()
    s20 = f"{100*tot20/d20[den].sum():.1f}%" if den else ""
    s24 = f"{100*tot24/d24[den].sum():.1f}%" if den else ""
    p = stats.ttest_rel(both[f"{col}_24"], both[f"{col}_20"]).pvalue
    print(f"{tag:18s} | {millions(tot20):>8s}M {millions(tot24):>8s}M |"
          f" {s20:>8s} {s24:>8s} | {100*(tot24-tot20)/tot20:+.1f}% {stars(p)}")
print(f"\nWrote {TEX / 'electorate_macros.tex'}")
print(f"Wrote {TEX / 'electorate_frame.tex'}")
