r"""
18_specifications.py

Reproducible "specifications" frames for the report: (1) a table of the main
estimating specifications with their sample restriction, control set, fixed
effects and N; (2) the first results for each -- first-stage strength and the
headline consolidation outcome (winner majority, P50).

Heterogeneity specs (open_seat / contested_seat) are deliberately excluded;
broader_treatment is excluded from the main frames (it weakens the first stage
to F<3 and is treated separately).

Source:
  output/tables/regressions/executive_margin_first_stage_fixest.csv
  output/tables/regressions/executive_margin_iv_fixest.csv
  data/estimation/executive_margin_design.csv   (to count controls that enter)

Writes:
  output/tables/tex/spec_macros.tex
  output/tables/tex/specifications_frame.tex
  output/tables/tex/spec_first_results_frame.tex
"""

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REG = ROOT / "output" / "tables" / "regressions"
TEX = ROOT / "output" / "tables" / "tex"
TEX.mkdir(parents=True, exist_ok=True)

fs = pd.read_csv(REG / "executive_margin_first_stage_fixest.csv")
iv = pd.read_csv(REG / "executive_margin_iv_fixest.csv")
cols = set(pd.read_csv(ROOT / "data" / "estimation" / "executive_margin_design.csv",
                       nrows=2).columns)

# Control lists mirror code/03_estimation/02_iv_main.R (single source of the
# spec definitions); we only count how many actually enter the design.
BASELINE = ["log_pop_2010", "urban_share_2010", "log_income_pc_2010", "margin_2016",
            "log1p_total_valid_votes_2020", "margin_top1_top2_2020",
            "log1p_total_candidates_2020"]
EXT_ADD = ["enp_2016", "female_vote_share_2020", "nonwhite_vote_share_2020",
           "higher_education_vote_share_2020", "log1p_party_count_2020",
           "log1p_coalition_count_2020", "turnout_rate_2020", "null_rate_2020",
           "share_first_time_candidates_2020", "share_career_politicians_2020"]
n_base = sum(c in cols for c in BASELINE)
n_ext = n_base + sum(c in cols for c in EXT_ADD)

# spec -> (display tag, number of controls)
SPECS = {
    "baseline":          ("Base",   n_base),
    "single_zone":       ("Single", n_base),
    "extended_controls": ("Ext",    n_ext),
    "region_fe":         ("Meso",   n_base),
}

HEADLINE = "delta_winner_majority_2024_2020"


def stars(p):
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


M = ["% Auto-generated by code/04_analysis/18_specifications.py — do not edit by hand."]


def emit(name, val):
    M.append(f"\\providecommand{{\\{name}}}{{}}\\renewcommand{{\\{name}}}{{{val}}}")


emit("SpecNControlsBase", str(n_base))
emit("SpecNControlsExt", str(n_ext))

for spec, (tag, nctrl) in SPECS.items():
    f = fs[fs.spec == spec].iloc[0]
    v = iv[(iv.spec == spec) & (iv.outcome == HEADLINE)].iloc[0]
    emit(f"Spec{tag}N", f"{int(f.nobs):,}")
    emit(f"Spec{tag}Clusters", f"{int(f.n_clusters):,}")
    emit(f"Spec{tag}NControls", str(nctrl))
    emit(f"Spec{tag}FScoef", f"{f.coef:.3f}")
    emit(f"Spec{tag}FSse", f"{f.se:.3f}")
    emit(f"Spec{tag}F", f"{f.first_stage_F:.1f}")
    emit(f"Spec{tag}tFcv", f"{f.tF_cv:.2f}")
    emit(f"Spec{tag}WM", f"{v.coef:.3f}\\rlap{{$^{{{stars(v.p)}}}$}}")
    emit(f"Spec{tag}WMse", f"({v.se:.3f})")

(TEX / "spec_macros.tex").write_text("\n".join(M) + "\n", encoding="utf-8")

# ----------------------------------------------------------------------
# Frame 1: the specifications
# ----------------------------------------------------------------------
spec_frame = r"""% Auto-generated by code/04_analysis/18_specifications.py — do not edit by hand.
% Requires: \input spec_macros.tex in the preamble.
\begin{frame}{Specifications --- The Three Main Estimates}
\centering
\footnotesize
\renewcommand{\arraystretch}{1.25}
\begin{tabular}{l l c c r r}
  \toprule
  Specification & Sample & Controls & FE & \multicolumn{1}{c}{$N$} & \multicolumn{1}{c}{Clusters} \\
  \midrule
  Baseline          & All municipalities      & \SpecBaseNControls   & State & \SpecBaseN   & \SpecBaseClusters \\
  Single-zone       & One electoral zone only & \SpecSingleNControls & State & \SpecSingleN & \SpecSingleClusters \\
  Extended controls & All municipalities      & \SpecExtNControls    & State & \SpecExtN    & \SpecExtClusters \\
  Mesoregion FE     & All municipalities      & \SpecMesoNControls   & Meso  & \SpecMesoN   & \SpecMesoClusters \\
  \bottomrule
\end{tabular}

\vspace{6pt}
\begin{block}{What each specification does}
  \footnotesize
  \begin{itemize}\itemsep3pt
    \item \textbf{Baseline.} \SpecBaseNControls{} controls --- 2010 socioeconomic
      structure (log population, urban share, log income p.c.), the 2016 win margin,
      and the 2020 electoral baseline (log valid votes, top-two margin, log
      candidate count) --- absorbing state fixed effects. SE clustered by principal
      electoral zone. This is the reference estimate.
    \item \textbf{Single-zone.} Same controls and FE, but restricted to
      municipalities that form a \emph{single} electoral zone
      ($N=\SpecSingleN$). Here lawsuit exposure maps one-to-one to the
      municipality, so the instrument's assignment is cleanest --- a check that the
      effect is not an artefact of zones spanning several municipalities.
    \item \textbf{Extended controls.} Adds \the\numexpr\SpecNControlsExt-\SpecNControlsBase\relax{}
      political-composition controls to the baseline (effective number of parties
      2016; 2020 female / non-white / higher-education vote shares; party and
      coalition counts; turnout and null rates; first-time-candidate and
      career-politician shares), for \SpecExtNControls{} in total --- testing
      whether the effect survives conditioning on the prior political landscape.
    \item \textbf{Mesoregion FE.} Baseline controls, but absorbing IBGE
      \emph{mesoregion} fixed effects (137 sub-state economic regions) in place of
      the 27 state effects --- comparing municipalities within the same local
      economic region, a much tighter geographic contrast.
  \end{itemize}
\end{block}
\end{frame}"""

(TEX / "specifications_frame.tex").write_text(spec_frame + "\n", encoding="utf-8")

# ----------------------------------------------------------------------
# Frame 2: first results for each specification
# ----------------------------------------------------------------------
res_frame = r"""% Auto-generated by code/04_analysis/18_specifications.py — do not edit by hand.
% Requires: \input spec_macros.tex in the preamble.
\begin{frame}{Specifications --- First-Stage Results}
\centering
\footnotesize
\renewcommand{\arraystretch}{1.3}
\begin{tabular}{l r r r r}
  \toprule
  Specification & \multicolumn{1}{c}{$\hat\pi$} & \multicolumn{1}{c}{$F$}
   & \multicolumn{1}{c}{$tF_{\text{cv}}$} & \multicolumn{1}{c}{$N$} \\
  \midrule
  Baseline          & \SpecBaseFScoef   & \SpecBaseF   & \SpecBasetFcv   & \SpecBaseN \\
                    & (\SpecBaseFSse)   &              &                 & \\
  Single-zone       & \SpecSingleFScoef & \SpecSingleF & \SpecSingletFcv & \SpecSingleN \\
                    & (\SpecSingleFSse) &              &                 & \\
  Extended controls & \SpecExtFScoef    & \SpecExtF    & \SpecExttFcv    & \SpecExtN \\
                    & (\SpecExtFSse)    &              &                 & \\
  Mesoregion FE     & \SpecMesoFScoef   & \SpecMesoF   & \SpecMesotFcv   & \SpecMesoN \\
                    & (\SpecMesoFSse)   &              &                 & \\
  \bottomrule
\end{tabular}

\vspace{4pt}
\begin{block}{}
  \footnotesize
  $\hat\pi$ is the first-stage coefficient of the endogenous
  $\Delta\log(1+\text{adversarial lawsuits})$ on the Bartik instrument
  (cluster-robust SE in parentheses); $F$ is its first-stage $F$;
  $tF_{\text{cv}}$ is the Lee et al.\ (2022) weak-instrument critical value.
  The first stage is positive, precise and comparably strong across all four
  specifications ($\hat\pi\approx 0.80$, $F\approx 16$--$19$) --- the instrument's
  relevance does not hinge on the control set, on multi-zone municipalities, or on
  the geographic level of the fixed effects.
  The second-stage (outcome) results follow.
\end{block}
\end{frame}"""

(TEX / "spec_first_results_frame.tex").write_text(res_frame + "\n", encoding="utf-8")

# ----------------------------------------------------------------------
# Console
# ----------------------------------------------------------------------
print(f"controls: baseline={n_base}, extended={n_ext}")
print(f"{'spec':18s} | {'N':>6s} {'cl':>5s} | {'FScoef':>7s} {'F':>5s} {'tFcv':>5s} |"
      f" {'WM coef':>8s} {'se':>7s} {'p':>6s}")
for spec, (tag, nctrl) in SPECS.items():
    f = fs[fs.spec == spec].iloc[0]
    v = iv[(iv.spec == spec) & (iv.outcome == HEADLINE)].iloc[0]
    print(f"{spec:18s} | {int(f.nobs):>6,} {int(f.n_clusters):>5,} |"
          f" {f.coef:>7.3f} {f.first_stage_F:>5.1f} {f.tF_cv:>5.2f} |"
          f" {v.coef:>8.3f} {v.se:>7.3f} {v.p:>6.3f}{stars(v.p)}")
print(f"\nWrote {TEX/'spec_macros.tex'}, specifications_frame.tex, spec_first_results_frame.tex")
