# Shared LaTeX table formatting utilities
#
# Usage in any estimation/analysis R script:
#
#   source(file.path(dirname(SCRIPT_PATH), "..", "utils", "latex_tables.R"))
#
# where SCRIPT_PATH is defined at the top of the calling script as:
#   SCRIPT_PATH <- normalizePath(sys.frame(1)$ofile)   # when sourced
#   SCRIPT_PATH <- normalizePath(commandArgs()[4])       # when Rscript
#
# Functions exported:
#   stars(p)                       — LaTeX significance stars
#   fmt_num(x, digits)             — fixed-decimal formatting
#   fmt_coef(x, p, digits)         — coefficient + stars
#   fmt_se(x, digits)              — SE in parentheses
#   write_tex(lines, path, script) — write fragment with header

stars <- function(p) {
  ifelse(p < 0.01, "$^{**}$",
    ifelse(p < 0.05, "$^{*}$",
      ifelse(p < 0.10, "$^{\\dagger}$", "")))
}

fmt_num <- function(x, digits = 3) {
  formatC(round(x, digits), format = "f", digits = digits)
}

fmt_coef <- function(x, p, digits = 3) {
  paste0(fmt_num(x, digits), stars(p))
}

fmt_se <- function(x, digits = 3) {
  paste0("(", fmt_num(x, digits), ")")
}

# write a character vector of lines to a .tex file
write_tex <- function(lines, path, script = NULL) {
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  header <- c(
    if (!is.null(script)) paste0("% Auto-generated by ", script),
    "% Do not edit manually -- rerun the generating script to update",
    ""
  )
  writeLines(c(header, lines), con = path)
  cat("  Wrote:", path, "\n")
}
